version: '3'

services:

  dspback:
    image: dspback
    container_name: dspback
    volumes:
      - ./dspback:/dspback
    build:
      context: ./dspback
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 5002:5002
    restart: on-failure

  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
